[package]
name = "anti_debugger"
version = "0.1.0"
edition = "2024"
build   = "build.rs"

[build-dependencies]
cc = "1.2.29"

[dependencies]
cc = "1.2.29"
nix = { version = "0.30.1", features = ["signal"] }
